test multi-cluster in same ns, improved img handling
- simple test for 2 ics in the same namespace
- cache images loaded into minikube

Change-Id: If4f1a90dcd21e7dafe6f2e3acc48de11895cc39e

diff --git a/docker-images/mk-local b/docker-images/mk-local
--- a/docker-images/mk-local
+++ b/docker-images/mk-local
@@ -9,28 +9,44 @@ case $only in
     *) server=1; router=1; shell=1 ;;
 esac
 
-version=8.0.21
+version1=8.0.21
 version0=8.0.20
 
 DOCKER_IMAGE_DIR=${DOCKER_IMAGE_DIR:-/tmp/docker-images}
 mkdir -p $DOCKER_IMAGE_DIR
 
+function build() {
+    cmd=$1
+    repo=$2
+    image=$3
+    ver=$4
+
+    echo
+    echo "$repo/$image:$ver"
+    echo
+    image_id=$($cmd $repo $ver| tee /dev/fd/2 | grep 'Successfully built'|cut -d\  -f3)
+    if test "$image_id" = ""; then
+        echo "Build failed"
+        exit 1
+    fi
+
+    path=$DOCKER_IMAGE_DIR/$image:$ver
+    docker image save $repo/$image:$ver -o $path
+    echo $image_id > $path.txt
+    echo $repo/$image:$ver >> $path.txt
+}
+
 if [ $server -ne 0 ]; then
-    ./make_server.sh mysql $version
-    docker image save mysql/mysql-server:$version -o $DOCKER_IMAGE_DIR/mysql-server:$version
-    ./make_server.sh mysql $version0
-    docker image save mysql/mysql-server:$version0 -o $DOCKER_IMAGE_DIR/mysql-server:$version0
+    build ./make_server.sh mysql mysql-server $version1
+    build ./make_server.sh mysql mysql-server $version0
 fi
 
 if [ $shell -ne 0 ]; then
-    ./make_shell.sh mysql $version
-    docker image save mysql/mysql-shell:$version -o $DOCKER_IMAGE_DIR/mysql-shell:$version
+    build ./make_shell.sh mysql mysql-shell $version1
 fi
 
 if [ $router -ne 0 ]; then
-    ./make_router.sh mysql $version
-    docker image save mysql/mysql-router:$version -o $DOCKER_IMAGE_DIR/mysql-router:$version
-    ./make_router.sh mysql $version0
-    docker image save mysql/mysql-router:$version0 -o $DOCKER_IMAGE_DIR/mysql-router:$version0
+    build ./make_router.sh mysql mysql-router $version1
+    build ./make_router.sh mysql mysql-router $version0
 fi
 
